version: '3'
services:
  db:
    image: postgres:16.0
    restart: always
    container_name: pretix_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: with-love-iidc
      POSTGRES_USER: pretix_admin
      POSTGRES_DB: pretix_main
    command: -p 6543
    ports:
      - "6543:6543"
    networks:
      - pretix-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7.2.2-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--port", "6379"]
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - pretix-net
    volumes:
      - redis-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pretix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pretix_main
    volumes:
      - ./etc/pretix.cfg:/etc/pretix/pretix.cfg
      - data:/data
      - src:/pretix/src
    ports:
      - "8000:80"
    networks:
      - pretix-net
    depends_on:
      - db
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

networks:
  pretix-net:

volumes:
  src:
  data:
  redis-data:
  postgres-data:
